name: Update Metapackages

on:
  push:
    branches:
      - focal

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim

    steps:
    - name: Update metapackages
      run: ./update_metapackages.sh focal